### ISSUE TITLE
Implement Benching For Gestalt Tools

### ISSUE THREAD

**Issue by McGinleyT** [HLRichardson-Git/Gestalt-Tools#1]
Needs a benchmarking tool to analyze speed performance and ability to log other critical data. I plan on using Google's Benchmark library to assist in creating a benchmark tool for the Gestalt library.

**Comment by HLRichardson-Git** [comment]
Okay I figured out why the googlebenchmark library was not being linked in. It was two fold, first was that I wasn't "linking" the Gestalt library to the Gestalt Tools project. I fixed this by adding this on line 13: ```target_link_libraries (${This} PRIVATE Gestalt benchmark::benchmark)```  of the ```Gestlat-Tool/benches/CMakeLists.txt``` file. 

The second problem was that CMake didn't really know what to do because I had no executables, sources, bitches, etc. If you see in the Gestalt Library Gestalt/CMakeLists.txt I have all the sources :
```
set (Sources
    src/aes/aes.cpp
    src/aes/aesCore.cpp
    src/modes/ecb.cpp
    src/modes/cbc.cpp
    src/sha1/sha1.cpp
    src/sha1/sha1Core.cpp
    tools/utils.cpp
)

add_library (${Project_Name} STATIC ${Sources})
```
And using the ```add_library```, I point CMake to the sources.

I went ahead and added the source files for the two current algorithms in Gestalt, AES and SHA1. So as I add more, we will need to make more benches and we'll have to add those in the ```Gestalt-Tools/benches/CMakeLists.txt``` file.

For now you should be able to pull the changes, build and run. Then it should run the ```BM_Add``` benchmark I got online that I put in the ```aesBenches.cpp``` file.

### Problem to think about
For now when we run Gestalt-Tools it will run all the benches, and most likely all the other tools we may eventually add. The way I got around this in Gestalt so as to not run all the unit tests and filter for the ones I want was to use a command like: ```./tests --gtest_filter=TestAES*``` which would only run the AES unit tests. (You can see this im more detail in this stackoverflow question I asked and answered [here](https://stackoverflow.com/questions/78125583/how-to-run-specific-tests-in-cmake-project-with-googletest)).

But I was only able to do this in googletest, because the unit tests have a prefix you can give a test that you can use ```--gtest_filter``` to filter for. So hopefully google benches has something similar we can utilize.
